Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace iwp.Models
{
    public class Category
    {
        [Key][Required]
        public int categoryId { get; set; }
        [MaxLength(100)][Required]
        public string Name { get; set; }
        
        
    }
}

Models/News.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace iwp.Models
{
    public class News
    {
        [Key]
        public int haberId { get; set; }
        public string haberBasligi { get; set; }
        public string haberIcerigi { get; set; }
        public string haberResmi { get; set; }
        public string haberYazari { get; set; }
        public DateTime haberTarihi { get; set; } //
        public int haberTiklanmasi { get; set; }  //
        public string haberKaynagi { get; set; }
        public int categoryId { get; set; }
        public bool isHome {get; set;}

        public News()
        {
            haberTarihi = DateTime.Now;
            haberTiklanmasi = 0;
        }

    }
}

Models/NewsUpdateModel.cs
namespace iwp.Models
{
    public class NewsUpdateModel
    {
        public int Id { get; set; }
        public string haberBasligi { get; set; }
        public string haberIcerigi { get; set; }
        public string haberResmi { get; set; }
        public string haberYazari { get; set; }
        public string haberKaynagi { get; set; }
        public int categoryId { get; set; }
        public bool isHome { get; set; }
    }
}

Components/CategoriesViewComponent.cs
using iwp.Data;
using Microsoft.AspNetCore.Mvc;

namespace iwp.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {   
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
        }
    }
}

Controllers/AdminController.cs
using System;
using iwp.Data;
using iwp.Models;
using Microsoft.AspNetCore.Mvc;

namespace iwp.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult NewsList()
        {
            return View(NewsRepository.GetAllNews());
        }

        [HttpGet]
        public IActionResult CreateNews()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateNews(NewsUpdateModel newsUpdateModel)
        {
            var haber = new News()
            {
                haberBasligi = newsUpdateModel.haberBasligi,
                haberIcerigi = newsUpdateModel.haberIcerigi,
                haberKaynagi = newsUpdateModel.haberKaynagi,
                haberResmi = newsUpdateModel.haberResmi,
                haberYazari = newsUpdateModel.haberYazari,
                categoryId = newsUpdateModel.categoryId,
                isHome = newsUpdateModel.isHome
            };

            NewsRepository.AddNews(haber);
            return RedirectToAction("NewsList");
        }

        [HttpGet]
        public IActionResult EditNews(int? Id)
        {
            if (Id != null)
            {
                var entity = NewsRepository.GetNewsbyId((int)Id);
                if (entity != null)
                {
                    var haber = new NewsUpdateModel()
                    {
                        Id = entity.haberId,
                        haberBasligi = entity.haberBasligi,
                        haberIcerigi = entity.haberIcerigi,
                        haberKaynagi = entity.haberKaynagi,
                        haberResmi = entity.haberResmi,
                        haberYazari = entity.haberYazari,
                        categoryId = entity.categoryId,
                        isHome = entity.isHome
                    };
                    return View(haber);
                }
                else
                    return NotFound();
            }
            else
                return NotFound();
        }

        [HttpPost]
        public IActionResult EditNews(NewsUpdateModel newsUpdateModel)
        {
            var entity = NewsRepository.GetNewsbyId(newsUpdateModel.Id);
            if (entity == null)
            {
                return NotFound();
            }
            Console.WriteLine(newsUpdateModel.haberBasligi);
            entity.haberBasligi = newsUpdateModel.haberBasligi;
            entity.haberIcerigi = newsUpdateModel.haberIcerigi;
            entity.haberKaynagi = newsUpdateModel.haberKaynagi;
            entity.haberResmi = newsUpdateModel.haberResmi;
            entity.haberYazari = newsUpdateModel.haberYazari;
            entity.categoryId = newsUpdateModel.categoryId;
            entity.isHome = newsUpdateModel.isHome;
            NewsRepository.UpdateNews(entity);
            return RedirectToAction("NewsList");
        }

        
        public IActionResult DeleteNews(int Id)
        {
                var haber = NewsRepository.GetNewsbyId(Id);
                if (haber != null)
                {
                    NewsRepository.DeleteNews(haber);
                    return RedirectToAction("NewsList");
                }
                else return NotFound();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using iwp.Data;
using iwp.Entity;
using iwp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace iwp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Home()
        {   
            var haber = NewsRepository.Haberler;
            return View(haber);
            
        }
 
    }
}

Controllers/NewsController.cs
using System.Linq;
using iwp.Data;
using Microsoft.AspNetCore.Mvc;

namespace iwp.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult Read(int Id)
        {
            return View(NewsRepository.GetNewsbyId(Id));
        }

        public IActionResult Category(int Id)
        {
            var haberler = NewsRepository.Haberler;
            haberler = haberler.Where(c => c.categoryId == Id).ToList();
            return View(haberler);
        }

        public IActionResult Search(string q)
        {
            var haberler = NewsRepository.Haberler;
            if (!string.IsNullOrEmpty(q))
            {
                haberler = haberler.Where(h => h.haberBasligi
                .ToLower().Contains(q.ToLower()) || h.haberIcerigi.ToLower().Contains(q)).ToList();
            }
            return View(haberler);
        }
    }
}

Views/Admin/CreateNews.cshtml
@model NewsUpdateModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">


    <title>Haber Sitesi</title>


</head>

<style>
    body {
        padding-top: 70px;
    }

    .frm {
        padding-top: 30px;
        padding-left: 60px;
        padding-right: 60rem;
    }
</style>

<body class="bg-light">
    @await Html.PartialAsync("_navbar")

    <div class="frm">
        <h2>Haber ekle:</h2>
        <hr>
        <form asp-controller="Admin" asp-action="CreateNews" method="POST">
            <div class="form-group">
                <label>Haber Başlığı</label>
                <input type="text" class="form-control" asp-for="haberBasligi">
            </div>
            <div class="form-group">
                <label>Haber İçeriği</label>
                <input type="text" class="form-control" asp-for="haberIcerigi">
            </div>
            <div class="form-group">
                <label>Haber Kaynağı</label>
                <input type="text" class="form-control" asp-for="haberKaynagi">
            </div>
            <div class="form-group">
                <label>Editör</label>
                <input type="text" class="form-control" asp-for="haberYazari">
            </div>
            <div class="form-group">
                <label>Resim URL</label>
                <input type="text" class="form-control" asp-for="haberResmi">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Haber Kategorisi</label>
                <select class="form-control" asp-for="categoryId">
                    <option selected disabled>Kategori seçiniz</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="isHome" value="true">
                <label class="form-check-label">Ana sayfada göster</label>
            </div>
            <button type="submit" class="btn btn-primary">EKLE</button>
        </form>
    </div>



</body>

</html>

Views/Admin/EditNews.cshtml
@model NewsUpdateModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">


    <title>Haber Sitesi</title>


</head>

<style>
    body {
        padding-top: 70px;
    }

    .frm {
        padding-top: 30px;
        padding-left: 60px;
        padding-right: 60rem;
    }
</style>

<body class="bg-light">
    @await Html.PartialAsync("_navbar")

    <div class="frm">
        <h2>Haberi düzenle:</h2>
        <hr>
        <form asp-controller="Admin" asp-action="EditNews" method="POST">
            <input type="hidden" name="Id" value="@Model.Id">
            <div class="form-group">
                <label>Haber Başlığı</label>
                <input type="text" class="form-control" asp-for="haberBasligi">
            </div>
            <div class="form-group">
                <label>Haber İçeriği</label>
                <input type="text" class="form-control" asp-for="haberIcerigi">
            </div>
            <div class="form-group">
                <label>Haber Kaynağı</label>
                <input type="text" class="form-control" asp-for="haberKaynagi">
            </div>
            <div class="form-group">
                <label>Editör</label>
                <input type="text" class="form-control" asp-for="haberYazari">
            </div>
            <div class="form-group">
                <label>Resim URL</label>
                <input type="text" class="form-control" asp-for="haberResmi">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Haber Kategorisi</label>
                <select class="form-control" asp-for="categoryId">
                    <option selected disabled>Kategori seçiniz</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="isHome" value="true">
                <label class="form-check-label" for="exampleCheck1">Ana sayfada göster</label>
            </div>
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </form>
    </div>



</body>

</html>

Views/Admin/NewsList.cshtml
@model List<News>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">


    <title>Haber Sitesi</title>


</head>

<style>
    body {
        padding-top: 70px;
    }

    .Id {
        width: 10px;
    }

    .td-img {
        width: 200px;
        height: 150px;
    }

    div.row {
        padding-right: 25px;
        padding-left: 25px;
    }

    table.table-bordered {
        border: 2px solid black;
        margin-top: 20px;
    }

    table.table-bordered>thead>tr>th {
        border: 2px solid black;
    }

    table.table-bordered>tbody>tr>td {
        border: 2px solid black;
    }

    table.table-bordered>tbody>tr>th {
        border: 2px solid black;
    }

    i {
        font-size: 30px;
    }
</style>

<body class="bg-dark">
    @await Html.PartialAsync("_navbar")

    <div class="row">
        <div class="col-md-12">
            <h1 style="display: inline;" class="text-white">Tüm Haberler:</h1>
            <a style="float: right; margin-right: 10px;" href="/admin/createnews" class="btn btn-lg btn-success">HABER
                EKLE</a>
            <table class="table table-bordered table-striped table-dark">
                <thead>
                    <tr>
                        <th style="width: 30px;" scope="col">ID</th>
                        <th style="width: 210px;" scope="col">RESİM</th>
                        <th style="width: 600px;" scope="col">BAŞLIK</th>
                        <th style="width: 40px;" scope="col">SEÇİLMİŞ HABER</th>
                        <th style="width: 70px;" scope="col">TARİH</th>
                        <th style="width: 100px;" scope="col">EDİTÖR</th>
                        <th style="width: 200px;" scope="col">KONTROL</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var h in Model)
                    {
                        <tr>
                            <th scope="row">@h.haberId</th>
                            <td><a href="@h.haberResmi">Resmi görüntüle..</a></td>
                            <td>@h.haberBasligi</td>
                            <td>
                                @if (h.isHome)
                                {
                                    <i class="fas fa-check-square" style="color: green;"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times-circle" style="color: red;"></i>
                                }
                            </td>
                            <td>@h.haberTarihi.ToString("dd/MM/yyyy")</td>
                            <td>@h.haberYazari</td>
                            <td>
                                <form style="display: inline;" action="/admin/deletenews" method="POST">
                                    <input type="hidden" name="Id" value="@h.haberId">
                                    <button type="submit" class="btn btn-sm btn-danger mr-1">SİL</button>
                                </form>

                                <a href="/admin/editnews/@h.haberId" class="btn btn-sm btn-primary mr-1">DÜZENLE</a>
                                <a href="/news/read/@h.haberId" class="btn btn-sm btn-warning">HABERE GİT</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</body>

</html>

Views/Home/Home.cshtml
@model List<News>

    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
        </script>
        <title>Haber Sitesi</title>


    </head>

    <style>
        .newsSlider {
            display: inline-block;
            float: left;
            width: 60%;
            padding: 10px 10px 25px 15px;
            margin-left: 60px;
        }

        body {
            /*background-color: #212528;*/
            padding-top: 70px;
        }

        .top-img {
            display: inline;
            width: 250px;
            height: 172px;
        }

        .top-buttons {
            height: 100%;
            width: 100%;
        }

        .top-buttons:hover {
            opacity: 0.8;
            transition: 0.5;
        }

        .btn-group-vertical {
            width: 600px;
            padding-top: 10px;
            padding-left: 50px;
            padding-right: 25px;
        }

        .top-title {}

        .card {
            margin-top: 5px;
            margin-bottom: 5px;


        }

        .row {
            margin-left: 5px;
            margin-right: 5px;
        }

        .card-img-top {
            padding-top: 5px;
            padding-bottom: 5px;
            width: 390px;
            height: 200px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>

    <body class="bg-dark">
        @await Html.PartialAsync("_navbar")
        @await Html.PartialAsync("_scrollingNews")

        <br>

        <div>
            
            <div class="bd-example newsSlider w-80 h-50">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://pix10.agoda.net/hotelImages/568255/-1/041a32e55dffcb63d5fd44bd48e54d27.jpg?s=1024x768"
                                class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>First slide label</h5>
                                <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="https://pix10.agoda.net/hotelImages/568255/-1/041a32e55dffcb63d5fd44bd48e54d27.jpg?s=1024x768"
                                class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Second slide label</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="https://pix10.agoda.net/hotelImages/568255/-1/041a32e55dffcb63d5fd44bd48e54d27.jpg?s=1024x768"
                                class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Third slide label</h5>
                                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <div class="btn-group-vertical">
                @for (int i = 0; i < 3; i++) { string[] colorCodes={ "#A1051D" , "#C03032" , "#DF4D49" }; <a
                    href="/news/read/@Model[i].haberId" type="button" class="btn top-buttons"
                    style="background-color: @colorCodes[i];">
                    <div class="row w-100">
                        <img class="img-thumbnail top-img col-md-6" src="@Model[i].haberResmi" alt="haberResmi">
                        <h5 class="col-md-4 pl-4 text-left" style="display: inline;">@Model[i].haberBasligi</h5>
                    </div>

                    </a>
                    }
            </div>
        </div>

        <br> <br>

        <div class="row">
            @foreach (var haber in Model)
            {
            if (haber.isHome)
            {
            <div class="col-md-3">
                <a href="/news/read/@haber.haberId" class="card bg-light">
                    <img class="card-img-top img-thumbnail" src=@haber.haberResmi alt="haberResmi">
                    <div class="card-body">
                        <h5 class="card-title">@haber.haberBasligi</h5>
                        <p class="card-text"><small class="text-muted">@haber.haberTarihi tarihinde eklendi.</small></p>
                    </div>
                </a>
            </div>
            }
            }
        </div>

    </body>

    </html>

Views/Shared/Components/Categories/Default.cshtml
@model List<Category>
<style>
    .nav-item:hover{
        border-radius: 5px;
        background-color: #DF4D49;
        text-decoration: solid;
        transition: 0.5s;
    }
</style>
<ul class="navbar-nav mr-auto">
    @foreach (var c in Model)
    {
        @if (ViewBag.SelectedCategory == c.categoryId.ToString())
            ViewBag.tmp = "active bg-danger rounded";
        else
            ViewBag.tmp = "";
        <li class="nav-item mx-0.7 @ViewBag.tmp">
            <a href="/news/category/@c.categoryId" class="nav-link">@c.Name</a>
        </li>
    }
</ul>

Views/Shared/_navbar.cshtml
<style>
    .arama {
        background-color: wheat;
        color: white;
        border-color: black;

    }

    .arama:hover {
        transition: 0.3s;
        color: white;
        border-color: white;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-warning fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand" href="/">HABERLER</a>

        @await Component.InvokeAsync("Categories")
        <a style="margin-right: 15px" href="/admin/newslist" class="btn btn-danger btn-sm">ADMİN</a>
        <form action="/news/search" class="form-inline my-2 my-lg-0">
            <input name="q" class="form-control mr-sm-2" type="search" placeholder="Arama" aria-label="Search">
            <button class="btn btn-outline-light bg-secondary my-2 my-sm-0 arama" type="submit">Haberlerde Ara</button>
        </form>
    </div>
</nav>

Views/Shared/_scrollingNews.cshtml
@model List<News>

<html>
<style>
    marquee {
        color: white;
    }

    div {
        display: inline;
    }
</style>

<body>

    <marquee behavior="scroll" direction="left" scrollamount="12" 
            onmouseover="this.stop();" onmouseout="this.start();">
        @foreach (var h in Model)
        {
            <div>
                <span>@h.haberTarihi.ToString("dd/MM/yyyy")</span>
                <a href="/news/read/@h.haberId"> @h.haberBasligi</a>
                <span>...............//...............</span>
            </div>
        }
    </marquee>

</body>
</html>